@baseUrl = http://localhost:8080
@password = password123
@username = demo-{{$timestamp}}
@userEmail = demo-{{$timestamp}}@example.com

### Register user
POST {{baseUrl}}/api/auth/register
Content-Type: application/json
Accept: application/json

{
  "username": "{{username}}",
  "email": "{{userEmail}}",
  "password": "{{password}}"
}

> {% client.global.set("token", response.body.token); %}

### Login
POST {{baseUrl}}/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "{{userEmail}}",
  "password": "{{password}}"
}

> {% client.global.set("token", response.body.token); %}

### Get current user
GET {{baseUrl}}/api/users/me
Accept: application/json
Authorization: Bearer {{token}}
